@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package lekavar.lma.drinkbeer.gui.utilsborrowedfromMdiyo;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;
